services:
  api1:
    image: ghcr.io/fksegundo/rinha-rust-api:sha-a0290cf
    pull_policy: always
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api1.sock
      RINHA_EARLY_EXIT_THRESHOLD: "2500000"
      RINHA_WARMUP_QUERIES: "256"
      RINHA_PAYLOAD_WARMUP_REQUESTS: "256"
      RINHA_THREAD_POOL_SIZE: "48"
      RINHA_PRETOUCH_INDEX: "1"
    volumes:
      - sockets:/sockets
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.48"
          memory: "172M"

  api2:
    image: ghcr.io/fksegundo/rinha-rust-api:sha-a0290cf
    pull_policy: always
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api2.sock 
      RINHA_EARLY_EXIT_THRESHOLD: "2500000"
      RINHA_WARMUP_QUERIES: "256"
      RINHA_PAYLOAD_WARMUP_REQUESTS: "256"
      RINHA_THREAD_POOL_SIZE: "48"
      RINHA_PRETOUCH_INDEX: "1"
    volumes:
      - sockets:/sockets
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.48"
          memory: "172M"

  lb:
    image: ghcr.io/fksegundo/rinha-api-lb:sha-ee837aa
    pull_policy: always
    restart: always
    user: "0:0"
    ports:
      - "9999:9999"
    logging:
      driver: "none"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.04"
          memory: "6M"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m
