version: "3.9"

services:
  api1:
    image: ghcr.io/fksegundo/rinha-rust-api:latest
    pull_policy: always
    cpuset: "0"
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    environment:
      RINHA_FD_SOCKET: /sockets/api1.sock
      RINHA_SEARCH_MODE: "${RINHA_SEARCH_MODE:-key-first}"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165M"
  api2:
    image: ghcr.io/fksegundo/rinha-rust-api:latest
    pull_policy: always
    cpuset: "1"
    restart: always
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    environment:
      RINHA_FD_SOCKET: /sockets/api2.sock
      RINHA_SEARCH_MODE: "${RINHA_SEARCH_MODE:-key-first}"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165M"
  lb:
    image: ghcr.io/fksegundo/rinha-api-lb:latest
    cpuset: "2,3"
    user: "0:0"
    ports:
      - "9999:9999"
    environment:
      PORT: "9999"
      FD_UPSTREAMS: /sockets/api1.sock,/sockets/api2.sock
      WORKERS: "2"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20M"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
