services:
  api1:
    environment:
      RINHA_FD_EVENTED: ${RINHA_FD_EVENTED:-1}
      RINHA_PAYLOAD_WARMUP_REQUESTS: ${RINHA_PAYLOAD_WARMUP_REQUESTS:-256}
      RINHA_CLIENT_FD_PRECONFIGURED: ${RINHA_CLIENT_FD_PRECONFIGURED:-1}
      RINHA_BUF_POOL_INIT: ${RINHA_BUF_POOL_INIT:-512}
      RINHA_EPOLL_TIMEOUT_MS: ${RINHA_EPOLL_TIMEOUT_MS:-1}
      RINHA_MLOCK_INDEX: ${RINHA_MLOCK_INDEX:-1}
      RINHA_PRETOUCH_INDEX: ${RINHA_PRETOUCH_INDEX:-1}
      RINHA_SPIN_BEFORE_BLOCK_US: ${RINHA_SPIN_BEFORE_BLOCK_US:-50}
  api2:
    environment:
      RINHA_FD_EVENTED: ${RINHA_FD_EVENTED:-1}
      RINHA_PAYLOAD_WARMUP_REQUESTS: ${RINHA_PAYLOAD_WARMUP_REQUESTS:-256}
      RINHA_CLIENT_FD_PRECONFIGURED: ${RINHA_CLIENT_FD_PRECONFIGURED:-1}
      RINHA_BUF_POOL_INIT: ${RINHA_BUF_POOL_INIT:-512}
      RINHA_EPOLL_TIMEOUT_MS: ${RINHA_EPOLL_TIMEOUT_MS:-1}
      RINHA_MLOCK_INDEX: ${RINHA_MLOCK_INDEX:-1}
      RINHA_PRETOUCH_INDEX: ${RINHA_PRETOUCH_INDEX:-1}
      RINHA_SPIN_BEFORE_BLOCK_US: ${RINHA_SPIN_BEFORE_BLOCK_US:-50}
