services:
  api1:
    environment:
      RINHA_FD_EVENTED: ${RINHA_FD_EVENTED:-1}
      RINHA_PAYLOAD_WARMUP_REQUESTS: ${RINHA_PAYLOAD_WARMUP_REQUESTS:-256}
  api2:
    environment:
      RINHA_FD_EVENTED: ${RINHA_FD_EVENTED:-1}
      RINHA_PAYLOAD_WARMUP_REQUESTS: ${RINHA_PAYLOAD_WARMUP_REQUESTS:-256}
