version: "3.9"
services:
  api1:
    image: ghcr.io/fksegundo/rinha-rust-api:latest
    pull_policy: always
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api1.sock
      RINHA_FD_EVENTED: "1"
      RINHA_CLIENT_FD_PRECONFIGURED: "1"
      RINHA_BUF_POOL_INIT: "512"
      RINHA_EPOLL_TIMEOUT_MS: "1"
      RINHA_MLOCK_INDEX: "1"
      RINHA_PRETOUCH_INDEX: "1"
      RINHA_SPIN_BEFORE_BLOCK_US: "50"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165M"

  api2:
    image: ghcr.io/fksegundo/rinha-rust-api:latest
    pull_policy: always
    restart: always
    network_mode: "none"
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api2.sock
      RINHA_FD_EVENTED: "1"
      RINHA_CLIENT_FD_PRECONFIGURED: "1"
      RINHA_BUF_POOL_INIT: "512"
      RINHA_EPOLL_TIMEOUT_MS: "1"
      RINHA_MLOCK_INDEX: "1"
      RINHA_PRETOUCH_INDEX: "1"
      RINHA_SPIN_BEFORE_BLOCK_US: "50"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165M"

  lb:
    image: ghcr.io/fksegundo/rinha-api-lb:latest
    pull_policy: always
    restart: always
    user: "0:0"
    ports:
      - "9999:9999"
    logging:
      driver: "none"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20M"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
