version: "3.9"

services:
  api1:
    image: ${APP_IMAGE:-rinha-rust-api:local}
    build:
      context: .
      dockerfile: submission/Dockerfile
    environment:
      RINHA_FD_SOCKET: /sockets/api1.sock
      RINHA_SEARCH_MODE: "${RINHA_SEARCH_MODE:-key-first}"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT:-0.42}"
          memory: "${API_MEMORY_LIMIT:-165M}"
  api2:
    image: ${APP_IMAGE:-rinha-rust-api:local}
    build:
      context: .
      dockerfile: submission/Dockerfile
    environment:
      RINHA_FD_SOCKET: /sockets/api2.sock
      RINHA_SEARCH_MODE: "${RINHA_SEARCH_MODE:-key-first}"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT:-0.42}"
          memory: "${API_MEMORY_LIMIT:-165M}"
  lb:
    image: ${LB_IMAGE:-rinha-lb:local}
    ports:
      - "9999:9999"
    environment:
      PORT: "9999"
      FD_UPSTREAMS: /sockets/api1.sock,/sockets/api2.sock
      WORKERS: "${LB_WORKERS:-2}"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${LB_CPU_LIMIT:-0.16}"
          memory: "${LB_MEMORY_LIMIT:-20M}"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
